Description:  network for simpleWebapp 

Parameters:
  EnvironmentName:
    Description: all resource name next prefix
    Type: String
    Default: BullsAndCows
  VpcCIDR:
    Description: vpc ipaddres
    Type: String
    Default: 10.0.0.0/18
  PublicSubnet1CIDR:
    Description: public cidr ipaddres
    Type: String
    Default: 10.0.1.0/24    
  PublicSubnet2CIDR:
    Description: public cidr ipaddres
    Type: String
    Default: 10.0.3.0/24   
  PrivateSubnet1CIDR:
    Description: public cidr ipaddres
    Type: String
    Default: 10.0.2.0/24    
  PrivateSubnet2CIDR:
    Description: public cidr ipaddres
    Type: String
    Default: 10.0.4.0/24   

Resources:
  # VPCの作成とigwのアタッチ
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true 
      Tags:
        - Key: Name
          Value: !Sub vpc-${EnvironmentName}
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub igw-${EnvironmentName}
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  # サブネットの作成
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-public-1a
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]  
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-public-3a
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-private-2a
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]   
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-private-4a     
  # ルートテーブルの作成
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub rtb-${EnvironmentName}
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

Outputs:
  #別スタックに値を渡すためのエクスポート
  VPCID:
    Value: !Ref VPC
    Export:
      Name: Vpc-ID
  PubSubnet1:
    Value: !Ref PublicSubnet1
    Export:
      Name: PublicSubnet1-ID
  PubSubnet2:
    Value: !Ref PublicSubnet2
    Export:
      Name: PublicSubnet2-ID  
  PvSubnet1:
    Value: !Ref PrivateSubnet1
    Export:
      Name: PvSubnet1-ID  
  PvSubnet2:
    Value: !Ref PrivateSubnet2
    Export:
      Name: PvSubnet2-ID  